kafka:
  topic: "real-time-reader"
  source: "prices.csv"
  bootstrap_server: "localhost:9092"

spark:
  spark_kafka_jar: "org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.2"
  

postgres:
  postgres_jar: "/mnt/c/users/leona/documents/personal/portfolio/Real Time Price Reader/postgresql-42.7.5.jar"
  server: "localhost:5432"
  database: "leo_local_db"
  table: "funds"

